### PR TITLE
Updating gradle plug-in version to 1.0.+

### LINKED ISSUE #12: Project uses unsupported version of the Gradle plug-in
When importing the project into Android Studio the following message is received:

Error:The project is using an unsupported version of the Android Gradle plug-in (0.12.2). The recommended version is 1.0.0.

### PR DESCRIPTION
**Pull request by dturner**
Fixes #12

### CODE REVIEW

**Comment by chaiwhat8** [comment]
Please feedbac my phone

**Comment by chaiwhat8** [comment]
feedback thanks

**Comment by claywilkinson** [comment]
Thanks for your pull request.

It looks like this may be your first contribution to a Google open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at https://cla.developers.google.com/.

If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check the information on your CLA or see this help article on setting the email on your git commits.

Once you've done that, please reply here to let us know. If you signed the CLA as a corporation, please let us know the company's name.

**Comment by samtstern** [comment]
This repository is now deprecated, closing all issues.  See README.md for more information.

**Pull request closed without merging**
